// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3w7Axihj5MH9F--dbgfRDdscyIZITy5c',
    appId: '1:1099430720644:web:9105aa43acaec83ce0bed1',
    messagingSenderId: '1099430720644',
    projectId: 'loginapp-b7e71',
    authDomain: 'loginapp-b7e71.firebaseapp.com',
    storageBucket: 'loginapp-b7e71.appspot.com',
    measurementId: 'G-6PV8EKKDWY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxr1Qvnh9N8uX611QMflM1FBJpHgwsxhQ',
    appId: '1:1099430720644:android:eec50f118ef0a2ffe0bed1',
    messagingSenderId: '1099430720644',
    projectId: 'loginapp-b7e71',
    storageBucket: 'loginapp-b7e71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDleJzhY0hQuHiddETg3nYv9xeVwXHMXGI',
    appId: '1:1099430720644:ios:fb714b01a2f15231e0bed1',
    messagingSenderId: '1099430720644',
    projectId: 'loginapp-b7e71',
    storageBucket: 'loginapp-b7e71.appspot.com',
    iosClientId: '1099430720644-85148d52v106unb0tbofliu0mom233qr.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginapp',
  );
}
